spring:
    application:
        name: fake-notification

management:
    endpoints:
        web:
            exposure:
                include: "health,info"
    endpoint:
        health:
            probes:
                enabled: true